name: Test Playwright Scripts
on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: v20.18.2
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npx playwright test
